jobs:
  include:
    - stage: "liboctopipes-linux"
      language: c
      dist: trusty
      compiler: gcc
      os: linux
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-7
        - cmake
      before_script:
        - cd libs/liboctopipes/ && mkdir build/ && cd build/
      script:
        - cmake ..
        - make
        - make install DESTDIR=./out/
        - ./test_parser
    - stage: "liboctopipes-minGW"
      language: c
      os: windows
      compiler: gcc
      before_script:
        - cd libs/liboctopipes/
        - mkdir build/
        - cd build/
      script:
        - cmake ..
        - make
        - make install DESTDIR=out
        - test_parser.exe
