jobs:
  include:
    - stage: "rustypipes"
      language: rust
      rust: stable
      cache: cargo
      before_install:
        - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      script:
        - cd libs/rustypipes/
        - cargo build --verbose --all
        - cargo test --verbose --all -- --nocapture
        - export CARGO_INCREMENTAL=0
        - zip -0 ccov.zip `find . \( -name "YOUR_PROJECT_NAME*.gc*" \) -print`;
        - ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
        - bash <(curl -s https://codecov.io/bash) -f lcov.info;
      deploy:
        on:
          tags: true
    - stage: "liboctopipes-linux"
      language: c
      dist: trusty
      compiler: gcc
      os: linux
      before_script:
        - cd libs/liboctopipes/ && mkdir build/ && cd build/
      script:
        - cmake ..
        - make
        - make install DESTDIR=./out/
        - ./test_parser
        - ./test_client -t /tmp/pipe_tx -r /tmp/pipe_rx -c /tmp/pipe_cap
    - stage: "liboctopipes-minGW"
      language: c
      os: windows
      compiler: gcc
      before_script:
        - cd libs/liboctopipes/
        - mkdir build/
        - cd build/
      script:
        - cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        - mingw32-make
        - ./test_parser.exe
    - stage: "liboctopipespp-linux"
      language: cpp
      dist: trusty
      compiler: g++
      os: linux
      before_script:
        - cd libs/liboctopipespp/ && mkdir build/ && cd build/
      script:
        - cmake ..
        - make
        - make install DESTDIR=./out/
        - ./test_parserpp
        - ./test_clientpp -t /tmp/pipecpp_tx -r /tmp/pipecpp_rx -c /tmp/pipecpp_cap
    - stage: "liboctopipespp-minGW"
      language: cpp
      os: windows
      compiler: g++
      before_script:
        - cd libs/liboctopipespp/
        - mkdir build/
        - cd build/
      script:
        - cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        - mingw32-make
