jobs:
  include:
    - stage: "liboctopipes-linux"
      language: c
      dist: trusty
      compiler: gcc
      os: linux
      before_script:
        - cd libs/liboctopipes/ && mkdir build/ && cd build/
      script:
        - cmake ..
        - make
        - make install DESTDIR=./out/
        - ./test_parser
        - ./test_client -t /tmp/pipe_tx -r /tmp/pipe_rx -c /tmp/pipe_cap
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "liboctopipes-minGW"
      language: c
      os: windows
      compiler: gcc
      before_script:
        - cd libs/liboctopipes/
        - mkdir build/
        - cd build/
      script:
        - cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        - mingw32-make
        - ./test_parser.exe
    - stage: "liboctopipespp-linux"
      language: cpp
      dist: trusty
      compiler: g++
      os: linux
      before_script:
        - cd libs/liboctopipespp/ && mkdir build/ && cd build/
      script:
        - cmake ..
        - make
        - make install DESTDIR=./out/
        - ./test_parserpp
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "liboctopipespp-minGW"
      language: cpp
      os: windows
      compiler: g++
      before_script:
        - cd libs/liboctopipespp/
        - mkdir build/
        - cd build/
      script:
        - cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        - mingw32-make
        - ./test_parserpp.exe
