jobs:
  include:
    - stage: "rustypipes"
      language: rust
      rust: stable
      cache: cargo
      addons:
        apt:
          packages:
            - kcov
      script:
        - cd libs/rustypipes/
        - cargo build --verbose --all
        - cargo test --verbose --lib -- --nocapture
      after_success: |
        kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/rustypipes-* &&
        bash <(curl -s https://codecov.io/bash) &&
        echo "Uploaded code coverage"
      deploy:
        on:
          tags: true
    - stage: "liboctopipes-linux"
      language: c
      dist: trusty
      compiler: gcc
      os: linux
      before_script:
        - cd libs/liboctopipes/ && mkdir build/ && cd build/
      script:
        - cmake ..
        - make
        - make install DESTDIR=./out/
        - ./test_parser
        - ./test_client -t /tmp/pipe_tx -r /tmp/pipe_rx -c /tmp/pipe_cap
    - stage: "liboctopipes-minGW"
      language: c
      os: windows
      compiler: gcc
      before_script:
        - cd libs/liboctopipes/
        - mkdir build/
        - cd build/
      script:
        - cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        - mingw32-make
        - ./test_parser.exe
    - stage: "liboctopipespp-linux"
      language: cpp
      dist: trusty
      compiler: g++
      os: linux
      before_script:
        - cd libs/liboctopipespp/ && mkdir build/ && cd build/
      script:
        - cmake ..
        - make
        - make install DESTDIR=./out/
        - ./test_parserpp
        - ./test_clientpp -t /tmp/pipecpp_tx -r /tmp/pipecpp_rx -c /tmp/pipecpp_cap
    - stage: "liboctopipespp-minGW"
      language: cpp
      os: windows
      compiler: g++
      before_script:
        - cd libs/liboctopipespp/
        - mkdir build/
        - cd build/
      script:
        - cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        - mingw32-make
